import type { PromptPreset, PromptPresetCategory } from '../types'

const preset = (category: PromptPresetCategory, id: string, label: string, description: string, insertion: string, keywords = ''): PromptPreset => ({ id: `${category}.${id}`, category, label, description, insertion, keywords: `${label} ${description} ${keywords}`.toLowerCase().split(/\s+/) })

export const promptPresets: PromptPreset[] = [
  preset('continuity', 'single-take', 'Single Unbroken Take', 'Keep the whole clip in one continuous shot.', 'Continuity: one uninterrupted take from beginning to end. No cuts, dissolves, time jumps, or changes of location.', 'h3 one shot no cuts continuous'),
  preset('continuity', 'screen-direction', 'Preserve Screen Direction', 'Keep movement consistent across the shot.', 'Continuity: maintain the established left-to-right or right-to-left travel direction. Keep the camera on the same side of the action axis.', '180 degree axis geography'),
  preset('continuity', 'identity', 'Identity Lock', 'Preserve each assigned person throughout movement.', 'Continuity: preserve each assigned character’s face, proportions, hair, and distinguishing features through turns and partial occlusion. Keep different people distinct.', 'reference face consistency'),
  preset('continuity', 'wardrobe', 'Wardrobe Continuity', 'Keep the assigned outfit consistent.', 'Continuity: retain the assigned garments, colors, materials, layers, and accessories throughout the shot. Fabric may move naturally without changing the outfit.', 'costume clothing'),
  preset('continuity', 'prop-contact', 'Prop Contact', 'Keep a held object attached to the correct hand.', 'Continuity: maintain the same prop shape, size, and grip. Fingers remain in plausible contact with its surface until a deliberate release.', 'hands object grip'),
  preset('continuity', 'background', 'Stable Background', 'Keep architecture and fixed landmarks consistent.', 'Continuity: retain the layout, doors, windows, furniture, and fixed background landmarks. Reveal them through plausible camera parallax without morphing or duplication.', 'room geometry environment'),
  preset('continuity', 'exposure', 'Stable Exposure', 'Avoid brightness and color shifts between frames.', 'Continuity: maintain a consistent exposure, white balance, and lighting direction. Allow only motivated changes caused by visible lights or subject movement.', 'flicker color temporal'),
  preset('continuity', 'edit-handles', 'Clean Edit Handles', 'Leave a settled beginning and ending for editing.', 'Timing: briefly establish a stable opening pose, perform the requested action, and leave a short settled hold at the end for a clean edit.', 'trim editing start end'),
  preset('continuity', 'last-frame', 'Reach the Last Frame', 'For First + last mode with both frames attached.', 'Continuity: move naturally from the supplied first frame toward the supplied last frame. Resolve the action into its closing composition without a dissolve or sudden pose change.', 'first last transition fl2v'),
  preset('continuity', 'no-overlays', 'Clean Frame', 'Keep generated graphics out of the picture.', 'Presentation: no captions, subtitles, watermarks, interface graphics, or added text overlays.', 'clean output typography'),
  preset('movement', 'listening', 'Listening Reaction', 'A quiet reaction while another person speaks.', 'Performance: listen attentively with a restrained eye movement and one subtle change of expression. Keep the mouth relaxed and avoid speaking or exaggerated nodding.', 'dialogue reaction silent'),
  preset('movement', 'eye-line', 'Hold an Eyeline', 'Keep attention on the established target.', 'Performance: maintain a consistent eyeline toward the established person or object. Use natural blinks without wandering gaze or looking into the lens unless requested.', 'gaze eye contact'),
  preset('movement', 'weight-transfer', 'Grounded Weight Transfer', 'Make a change of stance physically readable.', 'Action: shift weight gradually through the hips and supporting foot before stepping. Keep planted feet grounded and the body balanced.', 'feet walking sliding'),
  preset('movement', 'reach-grasp', 'Reach and Grasp', 'One clear hand-to-object interaction.', 'Action: reach toward the target object, open the hand before contact, close the fingers around its surface, then lift smoothly while maintaining the grip.', 'hand prop contact'),
  preset('audio', 'foley', 'Synchronized Foley', 'Match physical sounds to visible contact.', 'Sound: place footsteps, cloth movement, and object contact precisely at the visible actions. Keep each sound grounded in the room perspective.', 'sync footsteps contact'),
  preset('audio', 'dialogue-space', 'Dialogue First Mix', 'Use when dialogue is enabled for the shot.', 'Sound: keep the requested speech clear and at a natural level. Place ambience underneath it, with no competing foreground voices or added score.', 'voice intelligibility mix'),
  preset('audio', 'offscreen', 'Offscreen Sound Cue', 'Suggest nearby activity without adding visible subjects.', 'Sound: a subtle offscreen cue comes from a consistent direction within the established environment. Do not introduce a new visible person or object to explain it.', 'spatial sound environment'),
  preset('audio', 'room-perspective', 'Consistent Room Acoustics', 'Keep distance and reverberation coherent.', 'Sound: match reverberation and high-frequency detail to the visible room and source distance. Preserve the same acoustic space throughout the shot.', 'reverb ambience interior'),
  preset('shot', 'safe-framing', 'Delivery Safe Framing', 'Leave room for later crops and reframing.', 'Framing: keep the main face, hands, and essential action away from the frame edges, with intentional headroom and enough space for modest delivery crops.', 'vertical social safe margins'),
  preset('shot', 'two-person-blocking', 'Two-Person Blocking', 'Keep both people and their relationship readable.', 'Blocking: give each person a distinct position and consistent eyeline. Preserve clear silhouettes and avoid crossing or merging bodies during the exchange.', 'two shot dialogue staging'),
  preset('camera', 'static', 'Static', 'Locked composition with no camera motion.', 'Camera: locked-off static camera on a stable tripod, maintaining identical framing throughout.'),
  preset('camera', 'slow-push-in', 'Slow Push In', 'Gentle approach toward the subject.', 'Camera: a slow, smooth cinematic push-in toward the subject, maintaining stable framing and natural perspective.', 'dolly approach dramatic'),
  preset('camera', 'slow-pull-back', 'Slow Pull Back', 'Gradually reveal more of the scene.', 'Camera: a slow, smooth pull-back that gradually reveals the surrounding environment while preserving a stable axis.'),
  preset('camera', 'dolly-in', 'Dolly In', 'Physical forward camera move.', 'Camera: a controlled dolly-in on the subject with natural perspective shift and steady cinematic motion.'),
  preset('camera', 'dolly-out', 'Dolly Out', 'Physical backward camera move.', 'Camera: a controlled dolly-out from the subject, revealing context with stable, natural perspective.'),
  ...['Tracking Left','Tracking Right','Side Tracking'].map((label, index) => preset('camera', `tracking-${index}`, label, 'Smooth lateral tracking movement.', `Camera: ${label.toLowerCase()} in a smooth stabilized move, matching the subject's pace and preserving screen direction.`)),
  ...['Orbit Left','Orbit Right','180° Orbit','360° Orbit'].map((label, index) => preset('camera', `orbit-${index}`, label, 'Controlled orbit around the subject.', `Camera: a smooth ${label.toLowerCase()} around the subject at constant distance, with stable anatomy and background parallax.`)),
  ...['Crane Up','Crane Down','Pedestal Up','Pedestal Down','Tilt Up','Tilt Down','Pan Left','Pan Right'].map((label, index) => preset('camera', `move-${index}`, label, 'Precise directional camera movement.', `Camera: a slow, controlled ${label.toLowerCase()} with stable framing and a deliberate cinematic endpoint.`)),
  preset('camera', 'handheld-subtle', 'Handheld Subtle', 'Restrained human-operated motion.', 'Camera: subtle handheld movement with gentle natural drift, no harsh shake, and consistently readable framing.'),
  preset('camera', 'handheld-documentary', 'Handheld Documentary', 'Responsive observational movement.', 'Camera: grounded documentary handheld operation, responsively following the action with controlled realistic shake.'),
  ...['Steadicam Follow','Shoulder Follow','Overhead Descent','Low-Angle Rise','Arc Around Subject','Rack Focus','Whip Pan','Locked Tripod'].map((label, index) => preset('camera', `special-${index}`, label, 'Production-ready camera direction.', `Camera: ${label.toLowerCase()} executed smoothly with clear subject priority and coherent screen direction.`)),
  ...[['extreme-wide','Extreme Wide','Environment dominates the frame.'],['wide','Wide','Full environment and subject blocking.'],['full-body','Full Body','Head-to-toe subject framing.'],['cowboy','Cowboy','Mid-thigh framing for body language.'],['medium','Medium','Waist-up conversational framing.'],['medium-close','Medium Close-Up','Chest-up emotional framing.'],['close-up','Close-Up','Face-led intimate framing.'],['extreme-close','Extreme Close-Up','Isolate a precise facial or object detail.'],['ots','Over-the-Shoulder','Foreground shoulder establishes eyeline.'],['pov','POV','Subjective point-of-view framing.'],['two-shot','Two-Shot','Two subjects share readable composition.'],['insert','Insert Shot','Isolate a meaningful object or action.']].map(([id,label,description]) => preset('shot', id, label, description, `Shot: ${label.toLowerCase()} composition; ${description.toLowerCase()} Maintain intentional headroom and clean visual hierarchy.`)),
  ...[['eye','Eye Level'],['low','Low Angle'],['high','High Angle'],['overhead','Overhead'],['ground','Ground Level'],['dutch','Dutch Angle'],['profile','Profile'],['three-quarter','Three-Quarter'],['rear','Rear Follow']].map(([id,label]) => preset('angle', id, label, 'Defines viewpoint and subject relationship.', `Camera angle: ${label.toLowerCase()}, preserving natural anatomy, readable spatial relationships, and intentional composition.`)),
  ...[['18','18mm','expansive ultra-wide perspective with strong spatial depth'],['24','24mm','wide environmental perspective with energetic depth'],['28','28mm','natural wide perspective with clear environment'],['35','35mm','cinematic environmental perspective with moderate depth of field'],['50','50mm','natural perspective with shallow, realistic depth of field'],['65','65mm','gentle compression with refined subject separation'],['85','85mm','portrait compression with soft background separation'],['100','100mm Macro','macro detail with very shallow precise focus'],['135','135mm','strong telephoto compression and isolated background'],['anamorphic','Anamorphic','cinematic horizontal field of view, oval bokeh, and restrained lens character']].map(([id,label,description]) => preset('lens', id, label, description, `Lens: ${label}, ${description}. Keep focus transitions physically plausible.`)),
  ...[['window','Soft Window Daylight'],['sunrise','Sunrise'],['golden','Golden Hour'],['overcast','Overcast'],['studio','Soft Studio'],['side','Dramatic Side Light'],['practical','Practical Interior'],['office','Fluorescent Office'],['moon','Moonlight'],['neon','Neon'],['candle','Candlelight'],['high','High Key'],['low','Low Key'],['silhouette','Silhouette']].map(([id,label]) => preset('lighting', id, label, 'Cinematic lighting setup.', `Lighting: ${label.toLowerCase()} with motivated sources, stable exposure, realistic skin response, and coherent shadows.`)),
  ...[['room','Room Tone'],['outdoor','Outdoor Ambience'],['city','City Ambience'],['office','Office Ambience'],['forest','Forest Ambience'],['vehicle','Vehicle Interior'],['crowd','Crowd Murmur'],['rain','Rain'],['wind','Wind'],['silence','Silence / No Music'],['cinematic','Cinematic Environmental Sound']].map(([id,label]) => preset('audio', id, label, 'Synchronized environmental audio.', `Sound: ${label.toLowerCase()}, spatially coherent and synchronized to visible action; ${id === 'silence' ? 'no music and no added score.' : 'no unnecessary music.'}`)),
  preset('style', 'photoreal', 'Cinematic Photorealism', 'Natural materials and restrained grading.', 'Visual treatment: cinematic photorealism, realistic skin and materials, restrained filmic contrast, and natural color separation.'),
  preset('style', 'documentary', 'Documentary Realism', 'Observational and naturally imperfect.', 'Visual treatment: grounded documentary realism with available-light texture, credible imperfections, and restrained grading.'),
  preset('style', 'commercial', 'Polished Commercial', 'Clean premium advertising finish.', 'Visual treatment: polished premium commercial photography, precise surfaces, controlled highlights, and elegant color grading.'),
  preset('movement', 'subtle', 'Subtle Performance', 'Small physically believable movement.', 'Action: restrained natural performance with subtle breathing, eye movement, and physically coherent body motion.'),
  preset('movement', 'confident', 'Confident Movement', 'Purposeful blocking and posture.', 'Action: confident, purposeful movement with clear intention, controlled posture, and natural weight transfer.'),
  preset('movement', 'still', 'Hold Still', 'Minimize subject movement.', 'Action: the subject holds the pose with only natural breathing and tiny eye movement; no unintended gestures or position drift.'),
  preset('movement', 'single-beat', 'One Clear Action', 'Keep a short clip readable and achievable.', 'Action: one clear, physically achievable action with a visible beginning, middle, and settled end state. Do not introduce a second event.', 'h3 minimax reliable short clip'),
  preset('movement', 'settle', 'Settle at End', 'Leave time for the final frame to stabilize.', 'Timing: complete the action before the final second, then hold a stable natural end pose and camera framing.', 'continuity final frame'),
  ...[['hard','Hard Cut'],['match','Match Cut'],['continuous','Continuous Movement'],['visual','Visual Continuation'],['fade','Fade'],['reveal','Reveal'],['whip','Whip Transition']].map(([id,label]) => preset('transition', id, label, 'Editorial or continuity transition.', `Transition: ${label.toLowerCase()} with coherent timing, screen direction, and visual continuity.`)),
  preset('transition', 'i2v-continuation', 'Exact I2V Continuation', 'Continue directly from the supplied opening frame.', 'Continuity: begin exactly from the supplied first frame; preserve framing, lighting, screen direction, pose, and motion state before introducing the next action.', 'first frame continuation seamless'),
  preset('audio', 'no-dialogue', 'No Dialogue', 'Lock the soundtrack to ambience and foley only.', 'Sound: natural ambience and synchronized physical sound only; no dialogue, narration, singing, lip-sync, captions, text overlays, or music.', 'silent speech suppress'),
  preset('audio', 'reference-voice', 'Reference Voice Role', 'Use an attached audio source only for requested vocal qualities.', 'Audio reference: use the assigned audio only for the requested voice timbre, cadence, rhythm, or sound texture; generate a new synchronized target soundtrack.', 'audio 1 voice cadence'),
  preset('style', 'continuity', 'Continuity Priority', 'Protect identity and scene anchors between shots.', 'Continuity: preserve the assigned identity, wardrobe, location geography, lighting direction, screen direction, and scale; do not merge people, swap outfits, or introduce unassigned props.', 'reference character location'),
  ...[
    ['drone-rise','Drone Rise','Rise smoothly to reveal the wider geography.'], ['drone-descent','Drone Descent','Descend from an aerial overview into the subject.'], ['jib-reveal','Jib Reveal','Lift past foreground cover into a clean reveal.'],
    ['gimbal-walkthrough','Gimbal Walkthrough','Move fluidly through the environment at human height.'], ['vehicle-mount','Vehicle Mount','Maintain a rigid camera relationship to a moving vehicle.'], ['parallax-slide','Parallax Slide','Slide laterally to separate foreground and background layers.'],
    ['leading-follow','Leading Follow','Move backward ahead of the walking subject.'], ['trailing-follow','Trailing Follow','Follow behind while preserving forward screen direction.'], ['micro-drift','Micro Drift','Add nearly imperceptible cinematic camera life.'],
    ['vertigo','Dolly Zoom','Dolly and counter-zoom for a controlled perspective shift.'], ['snap-zoom','Snap Zoom','Use one motivated rapid zoom to emphasize a beat.'], ['tabletop-slider','Tabletop Slider','Execute a short precise product-style slider move.'],
  ].map(([id,label,description]) => preset('camera', id, label, description, `Camera: ${description.toLowerCase()} Keep the move continuous, stabilized, and motivated by the subject's action.`)),
  ...[
    ['establishing','Establishing Shot','Clearly introduce the location and spatial relationships.'], ['master','Master Shot','Cover the complete scene and all primary blocking.'], ['group','Group Shot','Arrange several subjects in a readable ensemble composition.'],
    ['reaction','Reaction Shot','Prioritize a character’s immediate emotional response.'], ['cutaway','Cutaway','Briefly isolate contextual action away from the main subject.'], ['detail','Detail Shot','Show a precise tactile action or important surface detail.'],
    ['symmetry','Symmetrical Composition','Center the visual weight with deliberate bilateral balance.'], ['negative-space','Negative Space','Leave intentional open space to emphasize isolation or direction.'],
  ].map(([id,label,description]) => preset('shot', id, label, description, `Shot: ${label.toLowerCase()}; ${description.toLowerCase()} Preserve clean eyelines, headroom, and visual priority.`)),
  ...[
    ['worms-eye','Worm’s-Eye','Extreme low viewpoint looking upward.'], ['birds-eye','Bird’s-Eye','High vertical viewpoint that maps the scene below.'], ['flat-lay','Top-Down Flat Lay','Perfectly perpendicular overhead view.'],
    ['hip-level','Hip Level','Low conversational viewpoint with grounded body language.'], ['eyeline','Eyeline Match','Match the established gaze direction and subject height.'], ['subtle-cant','Subtle Cant','Apply a restrained off-level horizon for unease.'],
  ].map(([id,label,description]) => preset('angle', id, label, description, `Camera angle: ${description.toLowerCase()} Maintain intentional perspective, natural anatomy, and coherent screen direction.`)),
  ...[
    ['14','14mm','dramatic ultra-wide coverage with pronounced spatial depth'], ['20','20mm','immersive wide perspective with controlled edge distortion'], ['40','40mm','balanced cinematic perspective between wide and normal'],
    ['58','58mm','gentle vintage-normal compression and organic separation'], ['70','70mm','moderate telephoto compression for intimate coverage'], ['200','200mm','long-lens compression with strongly isolated planes'],
    ['split','Split Diopter','simultaneous near and far focal planes with a motivated dividing line'], ['tilt','Tilt-Shift','selective focus-plane control with corrected architectural geometry'],
  ].map(([id,label,description]) => preset('lens', id, label, description, `Lens: ${label}, ${description}. Preserve physically plausible focus, distortion, and depth of field.`)),
  ...[
    ['rim','Rim Light','A controlled edge light separates the subject from the background.'], ['rembrandt','Rembrandt Portrait','A soft key creates the classic triangular cheek highlight.'], ['butterfly','Butterfly Portrait','A frontal elevated key produces clean symmetrical facial modeling.'],
    ['tungsten','Motivated Tungsten','Warm practical fixtures motivate the scene’s key light.'], ['blue-hour','Blue Hour','Cool ambient dusk balances against warm practical lights.'], ['storm','Storm Light','Soft dim daylight shifts with distant storm illumination.'],
    ['volumetric','Volumetric Beams','Visible motivated light shafts pass through atmospheric haze.'], ['projector','Projector Light','Moving projected imagery shapes the subject and background.'], ['fire','Firelight','Warm irregular firelight flickers naturally across nearby surfaces.'],
    ['caustics','Water Caustics','Soft moving reflected patterns travel across surfaces.'], ['mixed','Mixed Color Temperature','Cool ambient and warm practical sources remain deliberately balanced.'], ['bounce','Soft Bounce','A broad bounced source produces natural wrap and gentle falloff.'],
  ].map(([id,label,description]) => preset('lighting', id, label, description, `Lighting: ${description} Maintain stable exposure, coherent shadows, realistic skin response, and motivated sources.`)),
  ...[
    ['dialogue','Clean Dialogue','Prioritize intelligible natural speech with consistent room perspective.'], ['footsteps','Footsteps','Synchronize footfalls to each visible contact and floor surface.'], ['cloth','Clothing Foley','Add restrained fabric movement synchronized to body motion.'],
    ['impact','Impact Foley','Give visible contacts precise weight and material character.'], ['mechanical','Mechanical Detail','Layer credible switches, motors, gears, and resonances.'], ['kitchen','Kitchen Ambience','Use subtle appliances, utensils, ventilation, and room tone.'],
    ['nature','Nature Bed','Layer insects, leaves, distant wildlife, and open-air perspective.'], ['ocean','Ocean Shore','Use spatial surf, wind, foam, and distant coastal ambience.'], ['thunder','Distant Thunder','Place low distant thunder naturally behind the immediate ambience.'],
    ['reverb','Large-Room Reverb','Match voices and effects to a convincing large interior acoustic.'], ['close-mic','Intimate Close Mic','Capture detailed breath and voice with restrained room presence.'], ['distant','Distant Perspective','Place the sound source far away with appropriate air and reflections.'],
  ].map(([id,label,description]) => preset('audio', id, label, description, `Sound: ${description} Keep timing synchronized, spatial placement coherent, levels natural, and add no unnecessary music.`)),
  ...[
    ['16mm','16mm Film','Textured grain, gentle halation, and compact documentary color.'], ['35mm','35mm Film','Fine grain, filmic highlight rolloff, and restrained cinematic color.'], ['70mm','70mm Epic','Large-format clarity, dimensional depth, and refined natural color.'],
    ['noir','Classic Noir','Monochrome contrast, sculpted shadows, and precise pools of light.'], ['neo-noir','Neo-Noir','Deep blacks, selective saturated color, and urban atmospheric texture.'], ['retro-future','Retro Futurism','Optimistic analog technology, tactile materials, and period color design.'],
    ['period','Period Drama','Historically grounded materials, restrained palette, and elegant composition.'], ['horror','Psychological Horror','Controlled negative space, uneasy stillness, and oppressive practical light.'], ['romance','Romantic Drama','Soft separation, intimate framing, and warm restrained color.'],
    ['music-video','Music Video','Bold graphic composition, rhythmic energy, and polished lighting.'], ['fashion','Editorial Fashion','Sculptural posing, refined surfaces, and precise editorial light.'], ['indie','Independent Film','Natural performances, available-light texture, and restrained camera language.'],
  ].map(([id,label,description]) => preset('style', id, label, description, `Visual treatment: ${description.toLowerCase()} Keep materials credible and the grade consistent throughout the shot.`)),
  ...[
    ['walk','Natural Walk','Walk with realistic stride timing, balance, and arm swing.'], ['run','Controlled Run','Run with coherent footfalls, momentum, and body mechanics.'], ['turn','Turn to Camera','Turn the head and torso naturally toward camera in one continuous action.'],
    ['glance','Subtle Glance','Shift the eyes first, followed by a restrained head movement.'], ['sit','Sit Down','Lower into the seat with believable balance, contact, and cloth response.'], ['stand','Stand Up','Rise with natural weight transfer and stable footing.'],
    ['reach','Reach','Extend the arm with shoulder participation and accurate hand targeting.'], ['pickup','Pick Up Object','Grip, lift, and settle the object with credible contact and weight.'], ['gesture','Conversational Gesture','Use restrained hand gestures timed naturally to speech.'],
    ['hair','Hair Response','Let hair react subtly to movement, gravity, and local airflow.'], ['fabric','Fabric Response','Let clothing fold and settle naturally with body motion.'], ['crowd','Background Crowd','Maintain varied low-priority background movement without distracting repetition.'],
    ['vehicle','Vehicle Motion','Preserve believable acceleration, suspension, wheel contact, and environmental parallax.'], ['dance','Choreographed Dance','Maintain rhythmic full-body coordination and consistent anatomy.'], ['fight','Controlled Action Beat','Stage one readable exchange with safe spacing, impact timing, and no anatomy distortion.'],
  ].map(([id,label,description]) => preset('movement', id, label, description, `Action: ${description} Maintain identity, anatomy, contact, momentum, and continuity from start to finish.`)),
  ...[
    ['dissolve','Cross Dissolve','Blend two moments smoothly with a deliberate overlap.'], ['dip-black','Dip to Black','Briefly pass through black to mark a clear break.'], ['foreground-wipe','Foreground Wipe','Let a nearby moving object naturally cover the frame.'],
    ['occlusion','Occlusion Transition','Hide the cut behind a full-frame obstruction.'], ['iris','Iris Transition','Open or close the visible frame through a controlled circular mask.'], ['timelapse','Time-Lapse Transition','Compress environmental change while preserving a fixed visual anchor.'],
    ['speed-ramp','Speed Ramp','Change playback energy smoothly around one motivated action beat.'], ['focus','Focus Transition','Move attention between subjects through a clean motivated focus pull.'],
  ].map(([id,label,description]) => preset('transition', id, label, description, `Transition: ${description} Preserve composition, screen direction, timing, and the intended narrative connection.`)),
  ...[
    ['push-past','Push Past Foreground','Move past a near foreground element into the action.'], ['reveal-doorway','Doorway Reveal','Enter or reveal the scene through a doorway or frame.'], ['locked-portrait','Locked Portrait','Hold an intimate portrait composition with no reframing.'], ['tabletop-orbit','Tabletop Orbit','Circle a product or prop at close range with controlled parallax.'], ['focus-rack-near','Rack Focus Near','Shift focus from the background into a near subject.'], ['focus-rack-far','Rack Focus Far','Shift focus from a near object to the background action.'],
  ].map(([id,label,description]) => preset('camera', id, label, description, `Camera: ${description.toLowerCase()} Keep focus, movement, and perspective physically plausible.`)),
  ...[
    ['clean-plate','Clean Plate','Hold an empty environment for compositing or an edit point.'], ['product-hero','Product Hero','Present one object with clear silhouette and surface detail.'], ['silhouette-profile','Silhouette Profile','Use a readable side silhouette against a separated background.'], ['dialogue-coverage','Dialogue Coverage','Keep eyelines, headroom, and screen direction consistent for an edit.'],
  ].map(([id,label,description]) => preset('shot', id, label, description, `Shot: ${description}. Preserve clean composition and the intended editorial purpose.`)),
  ...[
    ['softbox','Softbox Key','Large soft studio source with gentle wrap and controlled shadow.'], ['motivated-window','Motivated Window','Use an off-frame window as a believable directional key.'], ['night-exterior','Night Exterior','Balance practical pools of light with readable shadow detail.'], ['overhead-practical','Overhead Practical','Let a ceiling practical shape the scene with grounded falloff.'],
  ].map(([id,label,description]) => preset('lighting', id, label, description, `Lighting: ${description}. Maintain motivated sources, stable exposure, and believable shadows.`)),
  ...[
    ['breath','Breath and Room Tone','Keep close natural breathing subtle against the room perspective.'], ['rain-interior','Rain on Glass','Place rain, distant traffic, and soft interior room tone behind the action.'], ['market','Market Ambience','Use layered distant voices, movement, and stalls without overpowering dialogue.'], ['club','Club Interior','Use restrained bass spill, crowd texture, and room reflections.'],
  ].map(([id,label,description]) => preset('audio', id, label, description, `Sound: ${description}. Keep the mix synchronized, natural, and appropriate to the visible space.`)),
]

export const promptPresetCategories: Array<{ id: PromptPresetCategory; label: string }> = [
  { id: 'camera', label: 'Camera' }, { id: 'shot', label: 'Shot' }, { id: 'angle', label: 'Angle' }, { id: 'lens', label: 'Lens' },
  { id: 'lighting', label: 'Lighting' }, { id: 'audio', label: 'Audio' }, { id: 'style', label: 'Style' }, { id: 'movement', label: 'Movement' }, { id: 'transition', label: 'Transition' }, { id: 'continuity', label: 'Continuity' }, { id: 'character', label: 'Character' }, { id: 'wardrobe', label: 'Wardrobe' }, { id: 'location', label: 'Location' },
]

export function promptCommandScore(item: { category: string; label: string; description: string; keywords?: string[]; meta?: string }, query: string) {
  const normalized = query.toLowerCase().trim()
  if (!normalized) return 0
  const label = item.label.toLowerCase()
  const searchable = `${item.category} ${label} ${item.description} ${(item.keywords ?? []).join(' ')} ${item.meta ?? ''}`.toLowerCase()
  const tokens = searchable.split(/[^\p{L}\p{N}]+/u)
  const fuzzy = (word: string) => word.length >= 3 && tokens.some((token) => {
    if (token[0] !== word[0]) return false
    let index = 0
    for (const character of token) if (character === word[index]) index += 1
    return index === word.length
  })
  const words = normalized.split(/\s+/)
  if (!words.every((word) => searchable.includes(word) || fuzzy(word))) return Infinity
  if (label === normalized) return 0
  if (label.startsWith(normalized)) return 1
  if (label.includes(normalized)) return 2
  if (words.every((word) => searchable.includes(word))) return 3
  return 4
}

export function searchPromptPresets(query: string) {
  return promptPresets.filter((item) => Number.isFinite(promptCommandScore(item, query)))
    .sort((a, b) => promptCommandScore(a, query) - promptCommandScore(b, query))
}
