import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('minimax', {
  getObjectInfo: (url: string) => ipcRenderer.invoke('comfy:info', url),
  uploadImageData: (url: string, data: string) => ipcRenderer.invoke('comfy:upload-data', url, data),
  getOutputImage: (url: string, file: unknown) => ipcRenderer.invoke('comfy:output-image', url, file),
  saveComfyOutputImage: (url: string, file: unknown, outputDirectory: string) => ipcRenderer.invoke('comfy:save-output-image', url, file, outputDirectory),
  saveStillImage: (url: string, file: unknown, outputDirectory: string) => ipcRenderer.invoke('comfy:save-still-image', url, file, outputDirectory),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  getLegacyMigrationStatus: () => ipcRenderer.invoke('migration:legacy-status'),
  migrateLegacyData: (replaceBrowserStorage = false) => ipcRenderer.invoke('migration:run', replaceBrowserStorage),
  getGpuTelemetry: () => ipcRenderer.invoke('system:gpu-telemetry'),
  saveSettings: (settings: unknown) => ipcRenderer.invoke('settings:save', settings),
  exportWorkflowJson: (suggestedName: string, workflow: unknown) => ipcRenderer.invoke('workflow:export-json', suggestedName, workflow),
  setUiScale: (scale: number) => ipcRenderer.invoke('window:set-ui-scale', scale),
  chooseDirectory: (initialPath?: string) => ipcRenderer.invoke('dialog:directory', initialPath),
  chooseMedia: (type: 'image' | 'video' | 'audio') => ipcRenderer.invoke('dialog:media', type),
  scanModels: (settings: unknown) => ipcRenderer.invoke('models:scan', settings),
  getComfyStatus: (url: string) => ipcRenderer.invoke('comfy:status', url),
  submitPrompt: (url: string, prompt: unknown, clientId?: string) => ipcRenderer.invoke('comfy:submit', url, prompt, clientId),
  getQueue: (url: string) => ipcRenderer.invoke('comfy:queue', url),
  getHistory: (url: string, promptId: string) => ipcRenderer.invoke('comfy:history', url, promptId),
  cancelPrompt: (url: string, promptId: string) => ipcRenderer.invoke('comfy:cancel', url, promptId),
  uploadInput: (url: string, filePath: string) => ipcRenderer.invoke('comfy:upload', url, filePath),
  fileDataUrl: (filePath: string) => ipcRenderer.invoke('file:data-url', filePath),
  mediaUrl: (filePath: string) => ipcRenderer.invoke('file:media-url', filePath),
  extractVideoFrame: (source: string, position: number | 'last', outputDirectory: string, ffmpegPath: string) => ipcRenderer.invoke('video:frame', source, position, outputDirectory, ffmpegPath),
  extractVideoFrames: (source: string, positions: number[], outputDirectory: string, ffmpegPath: string) => ipcRenderer.invoke('video:frames', source, positions, outputDirectory, ffmpegPath),
  trimVideo: (source: string, start: number, end: number, outputDirectory: string, ffmpegPath: string) => ipcRenderer.invoke('video:trim', source, start, end, outputDirectory, ffmpegPath),
  joinVideos: (clips: unknown[], outputDirectory: string, ffmpegPath: string) => ipcRenderer.invoke('video:join', clips, outputDirectory, ffmpegPath),
  getRifeStatus: () => ipcRenderer.invoke('rife:status'),
  installRife: () => ipcRenderer.invoke('rife:install'),
  interpolateVideo: (source: string, outputDirectory: string, ffmpegPath: string, mode: 'fps-2x' | 'slow-motion') => ipcRenderer.invoke('rife:interpolate', source, outputDirectory, ffmpegPath, mode),
  showOutput: (outputPath: string) => ipcRenderer.invoke('shell:show-output', outputPath),
  trashOutput: (source: string) => ipcRenderer.invoke('outputs:trash', source),
  findLatestOutput: (outputPath: string, since: number, kind: 'video' | 'audio' = 'video') => ipcRenderer.invoke('outputs:latest', outputPath, since, kind),
  resolveOutput: (outputPath: string, file: { filename: string; subfolder?: string; type?: string }) => ipcRenderer.invoke('outputs:resolve', outputPath, file),
  listOllamaModels: (url: string, provider: 'ollama' | 'lmstudio' = 'ollama') => ipcRenderer.invoke('ollama:list', url, provider),
  generateWithOllama: (url: string, model: string, prompt: string, provider: 'ollama' | 'lmstudio' = 'ollama') => ipcRenderer.invoke('ollama:generate', url, model, prompt, provider),
  generateWithOllamaVision: (url: string, model: string, prompt: string, imagePaths: string[], provider: 'ollama' | 'lmstudio' = 'ollama') => ipcRenderer.invoke('ollama:vision', url, model, prompt, imagePaths, provider),
  generateStructuredWithOllama: (url: string, model: string, prompt: string, schema: Record<string, unknown>, provider: 'ollama' | 'lmstudio' = 'ollama', imagePaths: string[] = []) => ipcRenderer.invoke('ollama:structured', url, model, prompt, schema, provider, imagePaths),
  getLanStatus: () => ipcRenderer.invoke('lan:status'),
  syncMobileCharacters: (characters: unknown[]) => ipcRenderer.invoke('lan:sync-characters', characters),
  rotateLanToken: () => ipcRenderer.invoke('lan:rotate-token'),
  setWindowAlwaysOnTop: (enabled: boolean) => ipcRenderer.invoke('window:set-always-on-top', enabled),
})
