import { useCallback, useEffect, useRef, useState } from 'react'
import { Camera, Check, ChevronDown, Code, Plus, Scan, Sparkles, Trash2, X } from 'lucide-react'
import { SmartPromptEditor, type SmartInsertOption, type SmartPromptEditorHandle } from './SmartPromptEditor'
import { compileScene } from '../lib/h3SceneCompiler'
import { applySceneCommand, applySceneSuggestions, cameraOptions, defaultPreservedAttributes, extractSceneDialogue, parseStyleValues, resizeScene, setFrameZeroGuide, suggestScene, value, type Attribute, type Camera as CameraState, type ScenePromptState, type SceneReference } from '../lib/scenePromptState'
import '../scene-composer.css'
import { SceneIssues } from './SceneIssues'

export type SceneInspectorSelection = { kind: 'scene' } | { kind: 'reference'; id: string } | { kind: 'shot'; id: string }

function preserveSummary(ref: SceneReference) {
  if (ref.preserve.length) return `Preserving: ${ref.preserve.map(item => item[0].toUpperCase() + item.slice(1)).join(' · ')}`
  if (ref.file.referenceRole === 'wardrobe') return 'Wardrobe reference · enable Preserve to retain the outfit'
  return ref.anchor === 'opening' ? 'Frame 0 anchor · native 0.00s guide' : ref.anchor ? `${ref.anchor} frame anchor` : ref.audio?.layer || ref.videoRole || 'Reference only · choose what it guides'
}

export function SceneComposer({ state, onChange, options, onAddReference, onManageReferences, onRemoveCharacter, onUpdateReferenceFile, onAnalyzeReference, selection, onInspect }: { state: ScenePromptState; onChange(state: ScenePromptState): void; options: SmartInsertOption[]; onAddReference(): void; onManageReferences(): void; onRemoveCharacter(characterId: string): void; onUpdateReferenceFile?(path: string, file: SceneReference['file']): void; onAnalyzeReference?(path: string): Promise<Partial<Record<Attribute, string>>>; selection?: SceneInspectorSelection; onInspect?(selection: SceneInspectorSelection): void }) {
  const editor = useRef<SmartPromptEditorHandle>(null)
  const suggestionsTrigger = useRef<HTMLButtonElement>(null)
  const suggestionsClose = useRef<HTMLButtonElement>(null)
  const [activeShot, setActiveShot] = useState(0)
  const [analysis, setAnalysis] = useState<{ id: string; fields: Partial<Record<Attribute, string>> } | null>(null)
  const [analyzing, setAnalyzing] = useState('')
  const [analysisError, setAnalysisError] = useState('')
  const [referencesOpen, setReferencesOpen] = useState(false)
  const [shotsOpen, setShotsOpen] = useState(false)
  const [suggestionsOpen, setSuggestionsOpen] = useState(false)
  const closeSuggestions = useCallback(() => {
    setSuggestionsOpen(false)
    window.requestAnimationFrame(() => suggestionsTrigger.current?.focus())
  }, [])
  useEffect(() => {
    if (!suggestionsOpen) return
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') closeSuggestions()
    }
    window.addEventListener('keydown', onKeyDown)
    window.requestAnimationFrame(() => suggestionsClose.current?.focus())
    return () => window.removeEventListener('keydown', onKeyDown)
  }, [closeSuggestions, suggestionsOpen])
  const compiled = compileScene(state)
  const suggestions = suggestScene(state.scene)
  const shotIndex = Math.min(activeShot, state.shots.length - 1)
  const shot = state.shots[shotIndex]
  const camera = shotIndex === 0 ? state.camera : shot?.camera || {}
  const setCamera = (key: keyof CameraState, text: string) => onChange(shotIndex === 0 ? { ...state, camera: { ...state.camera, [key]: value(text) } } : { ...state, shots: state.shots.map((item, index) => index === shotIndex ? { ...item, camera: { ...item.camera, [key]: value(text) } } : item) })
  const updateRef = (id: string, update: Partial<SceneReference>) => onChange({ ...state, references: state.references.map(ref => ref.id === id ? { ...ref, ...update } : ref) })
  const setView = (view: ScenePromptState['view']) => onChange({ ...state, view, manualPrompt: view === 'manual' && !state.manualPrompt ? compiled.prompt : state.manualPrompt })
  const characterSource = (characterId: string, attribute: Attribute) => {
    const numbers = state.references
      .filter(ref => ref.ownerId === characterId && ref.preserve.includes(attribute))
      .map(ref => Number(compiled.references.find(item => item.id === ref.id)?.label.match(/\d+/)?.[0]))
      .filter(Number.isFinite)
      .sort((a, b) => a - b)
    if (!numbers.length) return 'Character Default'
    if (numbers.length > 1 && numbers.every((number, index) => index === 0 || number === numbers[index - 1] + 1)) return `Pictures ${numbers[0]}–${numbers.at(-1)}`
    return `${numbers.length === 1 ? 'Picture' : 'Pictures'} ${numbers.join(', ')}`
  }
  return <section className="scene-composer" aria-label="Scene Composer">
    <nav className="scene-view-tabs" aria-label="Scene editor view"><span>VIEW</span>{(['creative', 'compiled', 'manual'] as const).map(view => <button key={view} type="button" aria-pressed={state.view === view} className={state.view === view ? 'selected' : ''} onClick={() => setView(view)}>{view === 'creative' ? <Camera size={15} /> : <Code size={15} />}{view === 'creative' ? 'Scene' : view === 'compiled' ? 'Compiled' : 'Manual'}</button>)}</nav>
    {state.view === 'creative' ? <div className="scene-workbench">
      <div className={`scene-authoring ${selection?.kind === 'scene' ? 'selected' : ''}`} onFocusCapture={() => onInspect?.({ kind: 'scene' })} onClick={() => onInspect?.({ kind: 'scene' })}><div><div className="scene-heading scene-direction-heading"><div><strong>Scene direction</strong><small>Describe the subject, action, and visual intent.</small></div><div className="scene-heading-actions"><button type="button" title="Browse scene commands" onClick={() => editor.current?.open()}><Sparkles size={14} />Commands</button><button ref={suggestionsTrigger} type="button" onClick={() => setSuggestionsOpen(true)}><Scan size={14} />Suggestions{suggestions.length > 0 && <em>{suggestions.length}</em>}</button></div></div>
        <SmartPromptEditor ref={editor} id="scene-description" value={state.scene} onChange={scene => onChange({ ...state, scene })} ariaLabel="Scene" rows={6} placeholder="Same woman, same clothes, same kitchen. An extreme close-up as she notices something above the camera…" options={options} onCommand={(item, scene) => { const next = applySceneCommand({ ...state, scene }, item.category, item.label, item.insertion); onChange(next) }} />
      </div></div>
      <div className={`scene-section scene-major-panel scene-references-panel reference-filmstrip ${referencesOpen ? 'show-details' : 'compact'} ${state.references.length ? 'has-references' : 'needs-reference'}`}><div className="scene-heading"><strong>References <em>{state.references.length}</em></strong><button type="button" onClick={onManageReferences}>Browse library</button><button type="button" className="panel-collapse" aria-expanded={referencesOpen} onClick={() => setReferencesOpen(!referencesOpen)}><ChevronDown size={14} className={referencesOpen ? 'rotated' : ''} />{referencesOpen ? 'Hide details' : 'Show details'}</button></div>
        <div className="scene-reference-grid" role="region" aria-label="Reference strip" tabIndex={0}>{state.references.map(ref => <article key={ref.id} data-reference-id={ref.id} aria-current={selection?.kind === 'reference' && selection.id === ref.id ? 'true' : undefined} onFocusCapture={() => onInspect?.({ kind: 'reference', id: ref.id })} onClick={() => onInspect?.({ kind: 'reference', id: ref.id })} className={`scene-reference-card ${ref.anchor ? 'anchored' : ''} ${selection?.kind === 'reference' && selection.id === ref.id ? 'selected' : ''}`}>
          <div className="scene-reference-image">{ref.file.preview && ref.file.kind === 'image' ? <img src={ref.file.preview} alt={ref.name} /> : <span>{ref.file.kind.toUpperCase()}</span>}<b>{compiled.references.find(item => item.id === ref.id)?.label.replace(/[<>]/g, '')}</b>{ref.file.kind === 'image' && <em className="reference-framing-badge">{ref.file.crop?.fit === 'crop' ? 'FILL' : 'FIT'}</em>}{ref.anchor === 'opening' && <em className="opening-frame-badge">FRAME 0 ANCHOR · 0.00s</em>}</div><div className="scene-reference-body"><div className="reference-role-badges">{(ref.preserve.length ? ref.preserve : [ref.file.referenceRole || ref.audio?.layer || ref.videoRole || 'reference']).slice(0, 3).map(role => <span key={role}>{String(role).toUpperCase()}</span>)}</div><strong title={ref.name}>{ref.name}</strong>
          {ref.file.kind === 'image' && <label className="scene-reference-framing" onClick={(event) => event.stopPropagation()}>Framing<select aria-label={`${ref.name} framing`} value={ref.file.crop?.fit ?? 'contain'} onChange={(event) => { const file = { ...ref.file, crop: { fit: event.target.value as 'contain' | 'crop', x: ref.file.crop?.x ?? .5, y: ref.file.crop?.y ?? .5, zoom: ref.file.crop?.zoom ?? 1 } }; updateRef(ref.id, { file }); onUpdateReferenceFile?.(ref.file.path, file) }}><option value="contain">Fit</option><option value="crop">Fill</option></select></label>}
          {ref.file.kind === 'image' && <div className="scene-reference-toggles"><label title="Native MiniMaxH3AddGuide conditioning at frame_idx 0. Only one picture can be the Frame 0 anchor."><input type="checkbox" checked={ref.anchor === 'opening'} onChange={event => onChange(setFrameZeroGuide(state, event.target.checked ? ref.id : undefined))} />Frame 0 anchor</label><label title={ref.file.referenceRole === 'wardrobe' ? 'Keep this approved outfit on the character throughout the shot.' : 'Preserve selected attributes as reusable guidance without locking the generated opening frame.'}><input type="checkbox" aria-label={`Preserve ${ref.name}`} checked={!!ref.preserve.length} onChange={event => updateRef(ref.id, { preserve: event.target.checked ? defaultPreservedAttributes(ref) : [] })} />Reference only</label></div>}
          <small className={`scene-retained ${ref.file.referenceRole === 'wardrobe' && !ref.preserve.length ? 'scene-retained-warning' : ''}`}>{preserveSummary(ref)}</small>
          {ref.file.kind === 'image' && onAnalyzeReference && <button type="button" disabled={!!analyzing} onClick={async () => { setAnalyzing(ref.id); setAnalysisError(''); try { setAnalysis({ id: ref.id, fields: await onAnalyzeReference(ref.file.path) }) } catch (error) { setAnalysisError(error instanceof Error ? error.message : String(error)) } finally { setAnalyzing('') } }}>{analyzing === ref.id ? 'Analyzing…' : 'Analyze visual details'}</button>}
          {analysis?.id === ref.id && <div className="scene-analysis-review"><strong>Suggested observations <em>AI</em></strong>{Object.entries(analysis.fields).filter(([,text]) => text).map(([field,text]) => <p key={field}><b>{field}</b>: {text}</p>)}<button type="button" onClick={() => { updateRef(ref.id, { observed: { ...analysis.fields, ...Object.fromEntries(Object.entries(ref.observed).filter(([, text]) => !!text)) }, reviewed: false }); setAnalysis(null) }}>Apply observations</button><button type="button" onClick={() => setAnalysis(null)}>Dismiss</button><small>Your existing observations stay in place. Framing is observed separately from preservation.</small></div>}
          {ref.file.kind === 'video' && <label><input type="checkbox" checked={!!ref.embeddedAudio} onChange={event => updateRef(ref.id, { embeddedAudio: event.target.checked ? { relation: 'reference', layer: 'ambience', description: 'The video’s ambient sound texture; do not inherit speech or music.' } : undefined })} />Use video audio</label>}
          <button type="button" className="scene-reference-inspect" onClick={() => onInspect?.({ kind: 'reference', id: ref.id })}>Edit in inspector <ChevronDown size={12} /></button></div></article>)}<button type="button" className="scene-add-reference" onClick={onAddReference}><Plus size={20} />Add reference<small>Image · Video · Audio</small></button></div>
      </div>
      <div className="scene-section scene-major-panel scene-shot-panel"><div className="scene-heading"><strong>Shot plan</strong><span>{shot?.start.toFixed(2)} — {shot?.end.toFixed(2)}s</span><label>Clip duration<input aria-label="Clip duration" type="number" min="1" max="15" step="0.5" value={state.duration} onChange={event => onChange(resizeScene(state, +event.target.value))} /></label><button type="button" className="panel-collapse" aria-expanded={shotsOpen} onClick={() => setShotsOpen(!shotsOpen)}><ChevronDown size={14} className={shotsOpen ? 'rotated' : ''} />{shotsOpen ? 'Collapse' : 'Expand'}</button></div>{shotsOpen && <><div className="scene-shot-tabs">{state.shots.map((item, index) => <button type="button" key={item.id} aria-current={selection?.kind === 'shot' && selection.id === item.id ? 'true' : undefined} className={index === shotIndex ? 'selected' : ''} onClick={() => { setActiveShot(index); onInspect?.({ kind: 'shot', id: item.id }) }}>Shot {index + 1}</button>)}<button type="button" disabled={!shot || shot.end - shot.start < 1} onClick={() => { const last = state.shots.at(-1)!; const split = Math.round((last.start + last.end) / 2 * 1000) / 1000; const id = `shot-${Date.now()}`; onChange({ ...state, shots: [...state.shots.slice(0, -1), { ...last, end: split }, { id, start: split, end: last.end, description: '', camera: {}, characterIds: [] }] }); setActiveShot(state.shots.length); onInspect?.({ kind: 'shot', id }) }}><Plus size={13} />Add shot</button>{state.shots.length > 1 && <button type="button" onClick={() => { const remaining = state.shots.filter((_, index) => index !== shotIndex); const next = remaining.map((item, index) => ({ ...item, start: index * state.duration / remaining.length, end: (index + 1) * state.duration / remaining.length })); onChange({ ...state, shots: next, dialogue: state.dialogue.filter(line => line.shotId !== shot.id) }); setActiveShot(0); onInspect?.({ kind: 'shot', id: next[0].id }) }}><Trash2 size={13} />Remove</button>}</div>
      <div className="scene-camera-grid">{Object.entries(cameraOptions).map(([key, choices]) => <label key={key}>{({ shotSize: 'Shot Size', angle: 'Camera Angle', movement: 'Camera Movement', speed: 'Speed', stabilization: 'Stabilization', amplitude: 'Movement Amount' } as Record<string, string>)[key]} <em>{camera[key as keyof CameraState]?.source || 'DEFAULT'}</em><select value={camera[key as keyof CameraState]?.value || ''} onChange={event => setCamera(key as keyof CameraState, event.target.value)}><option value="">From scene</option>{choices.map(choice => <option key={choice}>{choice}</option>)}{camera[key as keyof CameraState]?.value && !choices.includes(camera[key as keyof CameraState]!.value) && <option>{camera[key as keyof CameraState]!.value}</option>}</select></label>)}</div>
      {shot && <div className="scene-shot-detail"><input aria-label="Shot action" value={shot.description} placeholder="Additional action for this shot…" onChange={event => onChange({ ...state, shots: state.shots.map((item, index) => index === shotIndex ? { ...item, description: event.target.value } : item) })} /><label>End (s)<input type="number" min={shot.start + .01} max={state.duration} step="0.1" value={shot.end} onChange={event => onChange({ ...state, shots: state.shots.map((item, index) => index === shotIndex ? { ...item, end: +event.target.value } : index === shotIndex + 1 ? { ...item, start: +event.target.value } : item) })} /></label></div>}
      </>}
      </div>
      <div className="scene-lower-grid scene-details-grid"><details className="scene-section"><summary>Characters <em>{state.characters.length}</em></summary>
        {state.characters.map(character => <div className="scene-character" key={character.id}>
          <div className="scene-character-header"><div className="scene-character-portrait">{state.references.filter(ref => ref.ownerId === character.id && ref.file.preview && ref.preserve.some(attribute => ['identity', 'face', 'body'].includes(attribute))).slice(0, 3).map(ref => <img key={ref.id} src={ref.file.preview} alt={`${character.name} identity reference`} />)}<strong>{character.name}</strong></div><button type="button" className="scene-character-delete" aria-label={`Remove ${character.name} from scene`} title={`Remove ${character.name} from this scene`} onClick={() => onRemoveCharacter(character.id)}><Trash2 size={13} />Remove</button></div>
          <div className="character-source-rows">{(['identity', 'wardrobe', 'hair'] as Attribute[]).map(attribute => { const source = characterSource(character.id, attribute); return <div key={attribute}><span>{attribute[0].toUpperCase() + attribute.slice(1)}</span><strong>{character.attributes[attribute]?.value || source}</strong><em>{character.attributes[attribute]?.value ? character.attributes[attribute]?.source || 'USER' : source === 'Character Default' ? 'CHARACTER' : 'PRESERVE'}</em></div> })}</div>
          <details><summary>Assembly & canonical sources</summary>{(['identity', 'face', 'body', 'hair', 'wardrobe', 'accessories'] as Attribute[]).map(attribute => <label key={attribute}>{attribute} <em>{character.attributes[attribute]?.source || 'CHARACTER'}</em><input value={character.attributes[attribute]?.value || ''} placeholder="Explicit direction overrides Preserve" onChange={event => onChange({ ...state, characters: state.characters.map(item => item.id === character.id ? { ...item, attributes: { ...item.attributes, [attribute]: value(event.target.value) } } : item) })} /><select aria-label={`${character.name} ${attribute} source`} value={character.attributes[attribute]?.referenceIds?.[0] || ''} onChange={event => onChange({ ...state, references: state.references.map(ref => ref.ownerId === character.id ? { ...ref, preserve: ref.id === event.target.value ? [...new Set([...ref.preserve, attribute])] : ref.preserve.filter(item => item !== attribute) } : ref), characters: state.characters.map(item => item.id === character.id ? { ...item, attributes: { ...item.attributes, [attribute]: { ...value('', 'CHARACTER'), referenceIds: event.target.value ? [event.target.value] : [] } } } : item) })}><option value="">Assigned reference set</option>{state.references.filter(ref => ref.ownerId === character.id).map(ref => <option key={ref.id} value={ref.id}>{compiled.references.find(item => item.id === ref.id)?.label} · {ref.name}</option>)}</select></label>)}</details>
        </div>)}
        <button type="button" onClick={() => onChange({ ...state, characters: [...state.characters, { id: `character-${Date.now()}`, name: `Character ${state.characters.length + 1}`, attributes: {} }] })}>+ Add character</button>{state.characters.map(character => <input key={character.id} aria-label="Character name" value={character.name} onChange={event => onChange({ ...state, characters: state.characters.map(item => item.id === character.id ? { ...item, name: event.target.value } : item) })} />)}
      </details>
      <details className="scene-section" open={state.dialogue.length > 0 || undefined}><summary>Dialogue</summary>{state.dialogue.map(line => <div className="scene-dialogue" key={line.id}><select aria-label="Dialogue speaker" value={line.speakerIds[0] || ''} onChange={event => onChange({ ...state, dialogue: state.dialogue.map(item => item.id === line.id ? { ...item, speakerIds: [event.target.value] } : item) })}><option value="">Speaker</option>{state.characters.map(character => <option key={character.id} value={character.id}>{character.name}</option>)}</select>{(['language', 'delivery', 'text'] as const).map(field => <input key={field} aria-label={`Dialogue ${field}`} placeholder={field} value={line[field]} onChange={event => onChange({ ...state, dialogue: state.dialogue.map(item => item.id === line.id ? { ...item, [field]: event.target.value } : item) })} />)}<details><summary>Timing & delivery</summary><label>Shot<select value={line.shotId} onChange={event => onChange({ ...state, dialogue: state.dialogue.map(item => item.id === line.id ? { ...item, shotId: event.target.value, at: state.shots.find(shot => shot.id === event.target.value)!.start } : item) })}>{state.shots.map((shot, index) => <option key={shot.id} value={shot.id}>Shot {index + 1}</option>)}</select></label><label>Start (seconds)<input type="number" step="0.1" value={line.at} onChange={event => onChange({ ...state, dialogue: state.dialogue.map(item => item.id === line.id ? { ...item, at: +event.target.value } : item) })} /></label><label><input type="checkbox" checked={!!line.voiceover} onChange={event => onChange({ ...state, dialogue: state.dialogue.map(item => item.id === line.id ? { ...item, voiceover: event.target.checked } : item) })} />Off-screen voiceover</label><label>Across cuts<select value={line.continues || ''} onChange={event => onChange({ ...state, dialogue: state.dialogue.map(item => item.id === line.id ? { ...item, continues: event.target.value as typeof line.continues || undefined } : item) })}><option value="">Complete line</option><option value="to">Continues into next shot</option><option value="from">Continued from previous</option><option value="both">Both</option></select></label><label><input type="checkbox" checked={!!line.cutoff} onChange={event => onChange({ ...state, dialogue: state.dialogue.map(item => item.id === line.id ? { ...item, cutoff: event.target.checked } : item) })} />Cut off at clip end</label></details><button type="button" onClick={() => onChange({ ...state, dialogue: state.dialogue.filter(item => item.id !== line.id) })}>Remove line</button></div>)}<button type="button" disabled={!state.characters.length || !shot} onClick={() => onChange({ ...state, noDialogue: false, dialogue: [...state.dialogue, { id: `line-${Date.now()}`, shotId: shot.id, at: shot.start, speakerIds: [state.characters[0].id], language: 'English', text: '', delivery: '' }] })}>+ Add line</button></details>
      <details className="scene-section" open={!!(state.soundscape.value || state.music.value) || undefined}><summary>Sound & music</summary><label>Ambience & physical effects <em>{state.soundscape.source}</em><textarea rows={3} value={state.soundscape.value} onChange={event => onChange({ ...state, soundscape: value(event.target.value) })} /></label><label>Audience-only music <em>{state.music.source}</em><textarea rows={2} placeholder="No score unless requested" value={state.music.value} onChange={event => onChange({ ...state, music: value(event.target.value) })} /></label></details>
      <details className="scene-section"><summary>Environment & style</summary><label>Environment <em>{state.environment.source}</em><input value={state.environment.value} onChange={event => onChange({ ...state, environment: value(event.target.value) })} /></label><label>Lighting <em>{state.lighting.source}</em><input value={state.lighting.value} onChange={event => onChange({ ...state, lighting: value(event.target.value) })} /></label><label>Style chips<input placeholder="Found footage, Low-light, Realistic" value={state.styles.map(item => item.value).join(', ')} onChange={event => onChange({ ...state, styles: parseStyleValues(event.target.value) })} /></label></details></div>
    </div> : <div className="scene-section"><strong>{state.view === 'manual' ? 'Manual Override — edits are saved independently' : 'Deterministic H3 output'}</strong><p>{state.view === 'manual' ? 'Automatic recompilation will not replace this text. Reference and timing checks still run.' : 'This is the exact compiler output used for rendering.'}</p><textarea className="scene-compiled" aria-label={state.view === 'manual' ? 'Manual H3 prompt' : 'Compiled H3 prompt'} readOnly={state.view !== 'manual'} value={state.view === 'manual' ? state.manualPrompt : compiled.prompt} onChange={event => onChange({ ...state, manualPrompt: event.target.value })} /></div>}
    <SceneIssues conflicts={compiled.conflicts} state={state} onChange={onChange} onReferences={onManageReferences} />
    {analysisError && <p role="alert">{analysisError}</p>}
    {extractSceneDialogue(state).dialogue.length > state.dialogue.length && <button type="button" onClick={() => onChange(extractSceneDialogue(state))}>Review detected dialogue in structured controls</button>}
    <details className="scene-section scene-debug"><summary>H3 Debug / mapping inspector</summary><pre>{JSON.stringify({ mode: compiled.mode, subjects: compiled.subjects, references: compiled.references, timing: compiled.timing, speakerIDs: compiled.speakers, conflicts: compiled.conflicts }, null, 2)}</pre></details>
    {suggestionsOpen && <div className="modal-backdrop scene-suggestions-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) closeSuggestions() }}><section className="scene-suggestions-modal" role="dialog" aria-modal="true" aria-labelledby="scene-suggestions-title"><header><div><span><Scan size={17} /></span><div><small>SCENE ASSISTANT</small><strong id="scene-suggestions-title">Suggested camera choices</strong><p>Suggestions are inferred from your direction. Existing explicit choices and locks stay authoritative.</p></div></div><button ref={suggestionsClose} type="button" aria-label="Close suggestions" onClick={closeSuggestions}><X size={17} /></button></header><div className="scene-suggestions-list">{suggestions.length ? suggestions.map((item, index) => <article key={`${item.field}-${index}`} title={`Detected from: ${item.evidence}`}><span><Scan size={14} /></span><div><small>{item.field}</small><strong>{item.value}</strong><p>{item.evidence}</p></div><em>AI</em></article>) : <div className="scene-suggestions-empty"><Sparkles size={20} /><strong>No suggestions yet</strong><p>Describe the framing or camera behavior in Scene direction, then check again.</p></div>}</div><footer><span>{suggestions.length ? `${suggestions.length} suggested choice${suggestions.length === 1 ? '' : 's'}` : 'Nothing to apply'}</span><div><button type="button" onClick={closeSuggestions}>Cancel</button><button type="button" className="primary-button" disabled={!suggestions.length} onClick={() => { onChange(applySceneSuggestions(state)); closeSuggestions() }}><Check size={14} />Apply suggestions</button></div></footer></section></div>}
  </section>
}
