import { forwardRef, type ComponentPropsWithoutRef, type ElementRef, type HTMLAttributes, type InputHTMLAttributes, type TextareaHTMLAttributes } from 'react'
import { Check, ChevronDown, X } from 'lucide-react'
import { Slot } from '@radix-ui/react-slot'
import * as RadixTabs from '@radix-ui/react-tabs'
import * as RadixDialog from '@radix-ui/react-dialog'
import * as RadixAlertDialog from '@radix-ui/react-alert-dialog'
import * as RadixDropdown from '@radix-ui/react-dropdown-menu'
import * as RadixPopover from '@radix-ui/react-popover'
import * as RadixTooltip from '@radix-ui/react-tooltip'
import * as RadixSelect from '@radix-ui/react-select'
import * as RadixContext from '@radix-ui/react-context-menu'
import * as RadixSwitch from '@radix-ui/react-switch'
import * as RadixSlider from '@radix-ui/react-slider'
import * as RadixCheckbox from '@radix-ui/react-checkbox'
import * as RadixScroll from '@radix-ui/react-scroll-area'
import * as RadixSeparator from '@radix-ui/react-separator'
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '../../lib/cn'
import './ui.css'

const buttonStyles = cva('ui-button',{variants:{variant:{primary:'ui-button-primary',secondary:'ui-button-secondary',outline:'ui-button-outline',ghost:'ui-button-ghost',danger:'ui-button-danger',icon:'ui-button-icon'},size:{sm:'ui-button-sm',default:'',lg:'ui-button-lg'}},defaultVariants:{variant:'secondary',size:'default'}})
export interface ButtonProps extends ComponentPropsWithoutRef<'button'>,VariantProps<typeof buttonStyles>{asChild?:boolean}
export const Button=forwardRef<HTMLButtonElement,ButtonProps>(({className,variant,size,asChild,...props},ref)=>{const C=asChild?Slot:'button';return <C ref={ref} className={cn(buttonStyles({variant,size}),className)} {...props}/>});Button.displayName='Button'
export const Input=forwardRef<HTMLInputElement,InputHTMLAttributes<HTMLInputElement>>(({className,...props},ref)=><input ref={ref} className={cn('ui-input',className)} {...props}/>);Input.displayName='Input'
export const Textarea=forwardRef<HTMLTextAreaElement,TextareaHTMLAttributes<HTMLTextAreaElement>>(({className,...props},ref)=><textarea ref={ref} className={cn('ui-textarea',className)} {...props}/>);Textarea.displayName='Textarea'
export function Field({label,help,className,children}:HTMLAttributes<HTMLLabelElement>&{label:string;help?:string}){return <label className={cn('ui-field',className)}><span>{label}{help&&<small>{help}</small>}</span>{children}</label>}
export function Badge({tone='default',className,...props}:HTMLAttributes<HTMLSpanElement>&{tone?:'default'|'primary'|'success'|'warning'|'danger'}){return <span className={cn('ui-badge',tone!=='default'&&`ui-badge-${tone}`,className)} {...props}/>}
export const Separator=forwardRef<ElementRef<typeof RadixSeparator.Root>,ComponentPropsWithoutRef<typeof RadixSeparator.Root>>(({className,...props},ref)=><RadixSeparator.Root ref={ref} className={cn('ui-separator',className)} {...props}/>);Separator.displayName='Separator'
export const Tabs=RadixTabs.Root;export const TabsList=forwardRef<ElementRef<typeof RadixTabs.List>,ComponentPropsWithoutRef<typeof RadixTabs.List>>(({className,...props},ref)=><RadixTabs.List ref={ref} className={cn('ui-tabs-list',className)} {...props}/>);TabsList.displayName='TabsList';export const TabsTrigger=forwardRef<ElementRef<typeof RadixTabs.Trigger>,ComponentPropsWithoutRef<typeof RadixTabs.Trigger>>(({className,...props},ref)=><RadixTabs.Trigger ref={ref} className={cn('ui-tabs-trigger',className)} {...props}/>);TabsTrigger.displayName='TabsTrigger';export const TabsContent=forwardRef<ElementRef<typeof RadixTabs.Content>,ComponentPropsWithoutRef<typeof RadixTabs.Content>>(({className,...props},ref)=><RadixTabs.Content ref={ref} className={cn('ui-tabs-content',className)} {...props}/>);TabsContent.displayName='TabsContent'
export const Dialog=RadixDialog.Root;export const DialogTrigger=RadixDialog.Trigger;export const DialogClose=RadixDialog.Close;export function DialogContent({className,children,...props}:ComponentPropsWithoutRef<typeof RadixDialog.Content>){return <RadixDialog.Portal><RadixDialog.Overlay className="ui-dialog-overlay"/><RadixDialog.Content className={cn('ui-dialog-content',className)} {...props}>{children}<RadixDialog.Close className="ui-button ui-button-icon ui-button-ghost ui-dialog-close" aria-label="Close"><X size={15}/></RadixDialog.Close></RadixDialog.Content></RadixDialog.Portal>}export const DialogHeader=({className,...p}:HTMLAttributes<HTMLDivElement>)=><div className={cn('ui-dialog-header',className)} {...p}/>;export const DialogBody=({className,...p}:HTMLAttributes<HTMLDivElement>)=><div className={cn('ui-dialog-body',className)} {...p}/>;export const DialogFooter=({className,...p}:HTMLAttributes<HTMLDivElement>)=><div className={cn('ui-dialog-footer',className)} {...p}/>;export const DialogTitle=forwardRef<ElementRef<typeof RadixDialog.Title>,ComponentPropsWithoutRef<typeof RadixDialog.Title>>(({className,...p},r)=><RadixDialog.Title ref={r} className={cn('ui-dialog-title',className)} {...p}/>);DialogTitle.displayName='DialogTitle';export const DialogDescription=RadixDialog.Description
export const AlertDialog=RadixAlertDialog.Root;export const AlertDialogTrigger=RadixAlertDialog.Trigger;export const AlertDialogAction=RadixAlertDialog.Action;export const AlertDialogCancel=RadixAlertDialog.Cancel;export const AlertDialogTitle=RadixAlertDialog.Title;export function AlertDialogContent(p:ComponentPropsWithoutRef<typeof RadixAlertDialog.Content>){return <RadixAlertDialog.Portal><RadixAlertDialog.Overlay className="ui-dialog-overlay"/><RadixAlertDialog.Content className="ui-dialog-content" {...p}/></RadixAlertDialog.Portal>}
export const DropdownMenu=RadixDropdown.Root;export const DropdownMenuTrigger=RadixDropdown.Trigger;export const DropdownMenuItem=forwardRef<ElementRef<typeof RadixDropdown.Item>,ComponentPropsWithoutRef<typeof RadixDropdown.Item>>(({className,...p},r)=><RadixDropdown.Item ref={r} className={cn('ui-menu-item',className)} {...p}/>);DropdownMenuItem.displayName='DropdownMenuItem';export function DropdownMenuContent({className,...p}:ComponentPropsWithoutRef<typeof RadixDropdown.Content>){return <RadixDropdown.Portal><RadixDropdown.Content className={cn('ui-dropdown-content',className)} {...p}/></RadixDropdown.Portal>}
export const Popover=RadixPopover.Root;export const PopoverTrigger=RadixPopover.Trigger;export function PopoverContent({className,...p}:ComponentPropsWithoutRef<typeof RadixPopover.Content>){return <RadixPopover.Portal><RadixPopover.Content className={cn('ui-popover-content',className)} {...p}/></RadixPopover.Portal>}
export const TooltipProvider=RadixTooltip.Provider;export const Tooltip=RadixTooltip.Root;export const TooltipTrigger=RadixTooltip.Trigger;export function TooltipContent({className,...p}:ComponentPropsWithoutRef<typeof RadixTooltip.Content>){return <RadixTooltip.Portal><RadixTooltip.Content className={cn('ui-tooltip-content',className)} sideOffset={5} {...p}/></RadixTooltip.Portal>}
export const Select=RadixSelect.Root;export const SelectValue=RadixSelect.Value;export function SelectTrigger({className,children,...p}:ComponentPropsWithoutRef<typeof RadixSelect.Trigger>){return <RadixSelect.Trigger className={cn('ui-select-trigger',className)} {...p}>{children}<RadixSelect.Icon><ChevronDown size={13}/></RadixSelect.Icon></RadixSelect.Trigger>}export function SelectContent({className,...p}:ComponentPropsWithoutRef<typeof RadixSelect.Content>){return <RadixSelect.Portal><RadixSelect.Content className={cn('ui-select-content',className)} position="popper" {...p}><RadixSelect.Viewport>{p.children}</RadixSelect.Viewport></RadixSelect.Content></RadixSelect.Portal>}export function SelectItem({className,children,...p}:ComponentPropsWithoutRef<typeof RadixSelect.Item>){return <RadixSelect.Item className={cn('ui-select-item',className)} {...p}><RadixSelect.ItemText>{children}</RadixSelect.ItemText><RadixSelect.ItemIndicator><Check size={12}/></RadixSelect.ItemIndicator></RadixSelect.Item>}
export const ContextMenu=RadixContext.Root;export const ContextMenuTrigger=RadixContext.Trigger;export const ContextMenuItem=RadixContext.Item;export function ContextMenuContent(p:ComponentPropsWithoutRef<typeof RadixContext.Content>){return <RadixContext.Portal><RadixContext.Content className="ui-context-content" {...p}/></RadixContext.Portal>}
export const Switch=forwardRef<ElementRef<typeof RadixSwitch.Root>,ComponentPropsWithoutRef<typeof RadixSwitch.Root>>(({className,...p},r)=><RadixSwitch.Root ref={r} className={cn('ui-switch',className)} {...p}><RadixSwitch.Thumb className="ui-switch-thumb"/></RadixSwitch.Root>);Switch.displayName='Switch'
export const Checkbox=forwardRef<ElementRef<typeof RadixCheckbox.Root>,ComponentPropsWithoutRef<typeof RadixCheckbox.Root>>(({className,...p},r)=><RadixCheckbox.Root ref={r} className={cn('ui-checkbox',className)} {...p}><RadixCheckbox.Indicator><Check size={12}/></RadixCheckbox.Indicator></RadixCheckbox.Root>);Checkbox.displayName='Checkbox'
export const Slider=forwardRef<ElementRef<typeof RadixSlider.Root>,ComponentPropsWithoutRef<typeof RadixSlider.Root>>(({className,...p},r)=><RadixSlider.Root ref={r} className={cn('ui-slider',className)} {...p}><RadixSlider.Track className="ui-slider-track"><RadixSlider.Range className="ui-slider-range"/></RadixSlider.Track><RadixSlider.Thumb className="ui-slider-thumb"/></RadixSlider.Root>);Slider.displayName='Slider'
export function ScrollArea({className,children,...p}:ComponentPropsWithoutRef<typeof RadixScroll.Root>){return <RadixScroll.Root className={cn('ui-scroll-area',className)} {...p}><RadixScroll.Viewport className="ui-scroll-viewport">{children}</RadixScroll.Viewport><RadixScroll.Scrollbar className="ui-scrollbar"><RadixScroll.Thumb className="ui-scroll-thumb"/></RadixScroll.Scrollbar></RadixScroll.Root>}
export const Sheet=Dialog;export const SheetTrigger=DialogTrigger;export const SheetContent=DialogContent
export function ResizablePanel({className,...p}:HTMLAttributes<HTMLDivElement>){return <div className={cn('ui-resizable',className)} {...p}/>}
